index.html

@hartig here is a PR implementing (some of) the changes you have suggested. Feel free to comment.
NB: I *didn't* move the Conformance section into the Introduction after all, because the former is normative and the latter is not. Now that I think about it, we could remove the `informative` class from the Intro section, and put it on the relavant *sub-sections*, so the Conformance section would still be normative...

Structure changes suggested by Olaf

---

rdf-star-cg-spec.html

Initial proposals for standardized representations of embedded triples as RDF terms in SPARQL JSON results format and SPARQL XML result format.
Feedback on both content and markup much appreciated (I am relatively new at ReSpec).

GH-12 GH-13 basic specification of XML and JSON result formats

---

rdf-star-cg-spec.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/58.html" title="Last updated on Dec 11, 2020, 5:56 PM UTC (a713d3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/58/2160503...a713d3a.html" title="Last updated on Dec 11, 2020, 5:56 PM UTC (a713d3a)">Diff</a>

Annotation syntax for Turtle*

---

README.md

Inspite of the link, the associated Turtle, SPARQL, and JSON-LD implementations all have their own support for RDF*.

Indicates the Ruby RDF is SA only now

---

rdf-star-cg-spec.html

When Example 1 was changed to use different property names, the paragraph right after it was not updated to reflect the changes, so the edits in this branch do that.
***
<a href="https://pr-preview.s3.amazonaws.com/bobdc/rdf-star/pull/79.html" title="Last updated on Dec 24, 2020, 6:03 PM UTC (2d142c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/79/740deb3...bobdc:2d142c3.html" title="Last updated on Dec 24, 2020, 6:03 PM UTC (2d142c3)">Diff</a>

Updated paragraph to describe the revised version of Example 1.

---

tests/Makefile
tests/make-html-manifests.py
tests/make-jsonld-manifests.rb
tests/nt/syntax/manifest.jsonld
tests/semantics/manifest.ttl
tests/sparql/syntax/manifest.html
tests/sparql/syntax/manifest.jsonld
tests/sparql/syntax/manifest.ttl
tests/sparql/syntax/sparql-star-annotation-4.rq
tests/sparql/syntax/sparql-star-annotation-5.rq
tests/sparql/syntax/sparql-star-syntax-update-4.ru
tests/sparql/syntax/sparql-star-syntax-update-5.ru
tests/turtle/eval/manifest.html
tests/turtle/eval/manifest.jsonld
tests/turtle/eval/manifest.ttl
tests/turtle/eval/turtle-star-eval-embed-annotation-1.nt
tests/turtle/eval/turtle-star-eval-embed-annotation-1.ttl
tests/turtle/eval/turtle-star-eval-embed-annotation-2.nt
tests/turtle/eval/turtle-star-eval-embed-annotation-2.ttl
tests/turtle/eval/turtle-star-eval-embed-annotation-3.nt
tests/turtle/eval/turtle-star-eval-embed-annotation-3.ttl

@afs I didn't see a script for generating manifest.jsonld from manifest.ttl; I updated sparql/syntax/manifest.jsonld by hand, but didn't update turtle/eval/manifest.jsonld. I did build the HTML versions, however.

More combinations on embedded syntax

---

rdf-star-cg-spec.html

… as part of a new Concrete Syntaxes Section, which also includes Turtle*.
Fixes #16.
***
<a href="https://pr-preview.s3.amazonaws.com/gkellogg/rdf-star/pull/87.html" title="Last updated on Feb 9, 2021, 7:26 PM UTC (e5c223c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/87/9a5fdc0...gkellogg:e5c223c.html" title="Last updated on Feb 9, 2021, 7:26 PM UTC (e5c223c)">Diff</a>

Add N-Triples* and N-Quads* sections

---

rdf-star-cg-spec.html

```
s/The triple production produces an RDF* triple defined by the terms constructed for subject, predicate and object.
/The triple production produces an RDF* triple composed of a subject, predicate and object.
/
```
***
<a href="https://pr-preview.s3.amazonaws.com/ericprud/rdf-star/pull/91.html" title="Last updated on Feb 12, 2021, 7:53 AM UTC (e790c13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/91/0f804f5...ericprud:e790c13.html" title="Last updated on Feb 12, 2021, 7:53 AM UTC (e790c13)">Diff</a>

tweak description of N-Triples* triple production

---

rdf-star-cg-spec.html

source: https://lists.w3.org/Archives/Public/public-rdf-star/2021Jan/0059.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/88.html" title="Last updated on Feb 12, 2021, 6:37 PM UTC (2ad1ef3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/88/5c56a98...2ad1ef3.html" title="Last updated on Feb 12, 2021, 6:37 PM UTC (2ad1ef3)">Diff</a>

Alternative semantics based on @pfps' proposal

---

cg-spec/editors_draft.html

This PR is meant to address the SPARQL-star part of #9. That is, It adds the extension of the SPARQL-star grammar with the annotation syntax.
(the changes in this PR are copied over from #65 which was based on the old organization of files in the repo)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/106.html" title="Last updated on Feb 26, 2021, 5:08 PM UTC (c141ca5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/106/8b60d19...c141ca5.html" title="Last updated on Feb 26, 2021, 5:08 PM UTC (c141ca5)">Diff</a>

Annotation syntax for SPARQL-star

---

cg-spec/editors_draft.html

This PR removes the SPARQL-star version of BIND (a.k.a. FIND) as agreed during today's telco. The discussion that led to this decision is in #6
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/115.html" title="Last updated on Mar 1, 2021, 5:48 PM UTC (bbc64aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/115/9fbde7b...bbc64aa.html" title="Last updated on Mar 1, 2021, 5:48 PM UTC (bbc64aa)">Diff</a>

Removes the SPARQL-star version of BIND (a.k.a. FIND)

---

cg-spec/editors_draft.html

as flagged by @gatemezing
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/rdf-star/pull/125.html" title="Last updated on Mar 5, 2021, 2:38 PM UTC (da9f8d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/125/56089b2...TallTed:da9f8d7.html" title="Last updated on Mar 5, 2021, 2:38 PM UTC (da9f8d7)">Diff</a>

change "we we"  to "we"

---

cg-spec/editors_draft.html

This PR implements #108
/cc @pchampin @afs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/128.html" title="Last updated on Mar 5, 2021, 9:49 PM UTC (7a70b23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/128/3c42e4d...7a70b23.html" title="Last updated on Mar 5, 2021, 9:49 PM UTC (7a70b23)">Diff</a>

Adds the option for triples in the VALUES clause

---

tests/make-jsonld-manifests.rb
tests/manifest-context.jsonld
tests/manifest.ttl
tests/nt/syntax/manifest.html
tests/nt/syntax/manifest.jsonld
tests/nt/syntax/manifest.ttl
tests/semantics/manifest.html
tests/semantics/manifest.jsonld
tests/semantics/manifest.ttl
tests/sparql/eval/manifest.html
tests/sparql/eval/manifest.jsonld
tests/sparql/eval/manifest.ttl
tests/sparql/syntax/manifest.html
tests/sparql/syntax/manifest.jsonld
tests/sparql/syntax/manifest.ttl
tests/turtle/eval/manifest.html
tests/turtle/eval/manifest.jsonld
tests/turtle/eval/manifest.ttl
tests/turtle/syntax/manifest.html
tests/turtle/syntax/manifest.jsonld
tests/turtle/syntax/manifest.ttl

Follow on to #130.
1. Use `PREFIX trs:` ("test rdf star") for the test entries in manifest.ttl
2. Remove BASE usage so local files are accessed
Typical entry: URI is `<area#>`:
```
PREFIX trs:    <https://w3c.github.io/rdf-star/tests/semantics#>
```

manifest.ttl - no BASE; PREFIX trs

---

cg-spec/editors_draft.html
tests/sparql/syntax/manifest.jsonld
tests/sparql/syntax/manifest.ttl
tests/sparql/syntax/sparql-star-syntax-bad-11.rq
tests/sparql/syntax/sparql-star-syntax-bad-12.rq

Addresses issue #163.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/167.html" title="Last updated on May 6, 2021, 8:10 AM UTC (950082c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/167/ce2db5e...950082c.html" title="Last updated on May 6, 2021, 8:10 AM UTC (950082c)">Diff</a>

SPARQL-star: Add embedded triple pattern to PrimaryExpression, define evaluation.

---

tests/nt/syntax/manifest.jsonld
tests/nt/syntax/manifest.ttl

Minor: Noticed that two tests reference the wrong input file (even if the contents are the same).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/178.html" title="Last updated on Jun 4, 2021, 4:14 PM UTC (b377209)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/178/5b20a3f...b377209.html" title="Last updated on Jun 4, 2021, 4:14 PM UTC (b377209)">Diff</a>

Fix action links

---

implementations.html
reports/earl.jsonld
reports/earl.ttl
reports/index.html
reports/jena-report-2021-06-06.ttl

includes rebuilt `index.html` and `earl.*`.

Apache Jena implementation report (2021-06-06)

---

cg-spec/editors_draft.html

Adds an explicit Grammar section for TriG-star with modified `triplesOrGraph` production.
For #187.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/188.html" title="Last updated on Jun 12, 2021, 7:38 PM UTC (b276c4d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/188/561ce51...b276c4d.html" title="Last updated on Jun 12, 2021, 7:38 PM UTC (b276c4d)">Diff</a>

Trig-star productions

---

reports/earl.jsonld
reports/earl.ttl
reports/index.html
reports/template.haml
tests/semantics/manifest.ttl
tests/trig/syntax/manifest.ttl
tests/turtle/syntax/manifest.ttl

This fixes a problem with Semantics, Turtle Syntax and TriG Syntax manifests that incorrectly set the "trs" prefix used for the test entry IRIs.

Reports update

---

cg-spec/editors_draft.html

This addresses issue #3.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/224.html" title="Last updated on Dec 8, 2021, 3:08 PM UTC (873cc30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/224/a680f64...873cc30.html" title="Last updated on Dec 8, 2021, 3:08 PM UTC (873cc30)">Diff</a>

Conformance text

---

cg-spec/editors_draft.html

`:on` could also apply to the date it was extracted from dbpedia, which isn't the point of the example.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/227.html" title="Last updated on Dec 3, 2021, 8:06 AM UTC (4375e79)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/227/302abfa...4375e79.html" title="Last updated on Dec 3, 2021, 8:06 AM UTC (4375e79)">Diff</a>

change opacity `:on` to `:measuredOn`

---

reports/apache-jena.ttl

This Apache Jena report works more often than not with the rake step if the file has a timestamp that is more up-to-date than earl.* and index.html.
It differs from the file attached to #233 in that changing URIs from "http" to "https" for "homepage" in three places.

Add report: apache-jena.ttl

---

tests/sparql/syntax/sparql-star-syntax-bad-ann-path-2.rq
tests/sparql/syntax/sparql-star-syntax-bad-ann-path-3.rq
tests/sparql/syntax/sparql-star-syntax-bad-ann-path-4.rq
tests/sparql/syntax/sparql-star-syntax-bad-ann-path-5.rq
tests/sparql/syntax/sparql-star-syntax-bad-ann-path-6.rq

Object parts are missing in the patterns in tests
sparql-star-syntax-bad-ann-path-2.rq
sparql-star-syntax-bad-ann-path-3.rq
sparql-star-syntax-bad-ann-path-4.rq
sparql-star-syntax-bad-ann-path-5.rq
sparql-star-syntax-bad-ann-path-6.rq
This makes a correct SPARQL-star parser fail the tests as intended,
but for a different reason.

Add missing objects in `sparql-star-syntax-bad-ann-path-*.rq` tests

---

index.html

Put a link to the final community group report near the top of the home page.

Highlight the final report
