- UCR/RDFStarUCandRequirements.html
This copies the RDFStarUCandRequirements.html from the Easier RDF github repo.
It will be visible at 
https://w3c.github.io/rdf-star/UCR/RDFStarUCandRequirements.html
> Add a UC&R document (cloned from EasierRDF CG)

- tests/turtle/syntax/manifest.ttl
- tests/turtle/syntax/turtle-star-annotation-1.ttl
- tests/turtle/syntax/turtle-star-annotation-2.ttl
- tests/turtle/syntax/turtle-star-syntax-bad-01.ttl
- tests/turtle/syntax/turtle-star-syntax-bad-02.ttl
- tests/turtle/syntax/turtle-star-syntax-bad-03.ttl
- tests/turtle/syntax/turtle-star-syntax-bad-04.ttl
- tests/turtle/syntax/turtle-star-syntax-bad-05.ttl
- tests/turtle/syntax/turtle-star-syntax-basic-01.ttl
- tests/turtle/syntax/turtle-star-syntax-basic-02.ttl
- tests/turtle/syntax/turtle-star-syntax-bnode-01.ttl
- tests/turtle/syntax/turtle-star-syntax-bnode-02.ttl
- tests/turtle/syntax/turtle-star-syntax-bnode-03.ttl
- tests/turtle/syntax/turtle-star-syntax-compound.ttl
- tests/turtle/syntax/turtle-star-syntax-inside-01.ttl
- tests/turtle/syntax/turtle-star-syntax-inside-02.ttl
- tests/turtle/syntax/turtle-star-syntax-nested-01.ttl
- tests/turtle/syntax/turtle-star-syntax-nested-02.ttl
First draft of Turtle* syntax tests.
These are syntax tests. They test whether a parser accepts or rejects a file. There is no implication as what triples are generated which is left for a separate set of tests.
> Turtle* syntax tests

- UCR/rdf-star-ucr.html
issue #29 is not the only one related to UCS anymore
> update links to GH issues

- tests/nt/syntax/manifest.html
- tests/nt/syntax/manifest.ttl
- tests/nt/syntax/nt-ttl-star-syntax-4.ttl
- tests/nt/syntax/nt-ttl-star-syntax-5.ttl
- tests/nt/syntax/ntriples-star-syntax-4.nt
- tests/nt/syntax/ntriples-star-syntax-5.nt
- tests/turtle/syntax/manifest.html
- tests/turtle/syntax/manifest.ttl
- tests/turtle/syntax/turtle-star-syntax-bad-07.ttl
Includes a bad syntax test for empty annotation.
> More syntax tests

- index.html
This is definitely not a [substantive contribution](https://github.com/w3c/rdf-star/blob/main/CONTRIBUTING.md) so I'm opening this PR without being a CG member.
> Fix SPARQL* link

- rdf-star-cg-spec.html
This PR extends the authors list before creating our first working draft.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/96.html" title="Last updated on Feb 16, 2021, 7:32 AM UTC (fb396a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/96/9296a32...fb396a0.html" title="Last updated on Feb 16, 2021, 7:32 AM UTC (fb396a0)">Diff</a>
> update authors list

- cg-spec/editors_draft.html
Fixes #112.
@hartig You might want more expansion on the steps, as they are writing from the perspective of someone trying to parse a Turtle-star grammar.
***
<a href="https://pr-preview.s3.amazonaws.com/gkellogg/rdf-star/pull/113.html" title="Last updated on Feb 22, 2021, 6:05 PM UTC (fc95dba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/113/8b60d19...gkellogg:fc95dba.html" title="Last updated on Feb 22, 2021, 6:05 PM UTC (fc95dba)">Diff</a>
> Describe Turtle-star parser steps

- cg-spec/editors_draft.html
Adds a mailing list configuration, which is shown in the status section.
***
<a href="https://pr-preview.s3.amazonaws.com/gkellogg/rdf-star/pull/105.html" title="Last updated on Feb 22, 2021, 9:05 PM UTC (93163e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/105/f4a11bb...gkellogg:93163e8.html" title="Last updated on Feb 22, 2021, 9:05 PM UTC (93163e8)">Diff</a>
> Mailing list

- cg-spec/editors_draft.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/143.html" title="Last updated on Apr 7, 2021, 10:07 AM UTC (97107f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/143/318260c...97107f8.html" title="Last updated on Apr 7, 2021, 10:07 AM UTC (97107f8)">Diff</a>
> section on merge (address #135)

- cg-spec/editors_draft.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/158.html" title="Last updated on Apr 9, 2021, 10:49 PM UTC (79e5df9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/158/84746a7...79e5df9.html" title="Last updated on Apr 9, 2021, 10:49 PM UTC (79e5df9)">Diff</a>
> Reorder concrete syntaxes

- reports/earl.jsonld
- reports/earl.ttl
- reports/index.html
- reports/template.haml
> Minor corrections to implementation report template.

- cg-spec/editors_draft.html
in particular, addresses #93 by adding an example using the annotation syntax.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/155.html" title="Last updated on Apr 13, 2021, 3:06 PM UTC (8e92ed5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/155/e2c4ec1...8e92ed5.html" title="Last updated on Apr 13, 2021, 3:06 PM UTC (8e92ed5)">Diff</a>
> extend the Overview section

- index.html
> Link to implementation reports page

- cg-spec/editors_draft.html
addresses #94 and #165
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/171.html" title="Last updated on May 28, 2021, 11:38 AM UTC (e5abb6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/171/be79326...e5abb6b.html" title="Last updated on May 28, 2021, 11:38 AM UTC (e5abb6b)">Diff</a>
> Tidy up intro

- cg-spec/editors_draft.html
- tests/sparql/eval/data-7.ttl
- tests/sparql/eval/data-order-kind.ttl
- tests/sparql/eval/data-order.ttl
- tests/sparql/eval/manifest.html
- tests/sparql/eval/manifest.jsonld
- tests/sparql/eval/manifest.ttl
- tests/sparql/eval/sparql-star-op-1.rq
- tests/sparql/eval/sparql-star-op-1.srj
- tests/sparql/eval/sparql-star-op-2.rq
- tests/sparql/eval/sparql-star-op-2.srj
- tests/sparql/eval/sparql-star-op-3.rq
- tests/sparql/eval/sparql-star-op-3.srj
- tests/sparql/eval/sparql-star-op-4.rq
- tests/sparql/eval/sparql-star-op-4.srj
- tests/sparql/eval/sparql-star-order-1.rq
- tests/sparql/eval/sparql-star-order-1.srj
- tests/sparql/eval/sparql-star-order-2.srj
- tests/sparql/eval/sparql-star-order-by.rq
- tests/sparql/syntax/manifest.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/172.html" title="Last updated on May 30, 2021, 7:38 AM UTC (e3f609e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/172/b145830...e3f609e.html" title="Last updated on May 30, 2021, 7:38 AM UTC (e3f609e)">Diff</a>
> SPARQL Functions and Operators modifications + tests

- cg-spec/editors_draft.html
addresses #166
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/173.html" title="Last updated on Jun 4, 2021, 6:24 AM UTC (dccae50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/173/5b20a3f...dccae50.html" title="Last updated on Jun 4, 2021, 6:24 AM UTC (dccae50)">Diff</a>
> Discussion on referential opacity

- cg-spec/editors_draft.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/176.html" title="Last updated on Jun 9, 2021, 10:41 AM UTC (05a5db3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/176/660e6b9...05a5db3.html" title="Last updated on Jun 9, 2021, 10:41 AM UTC (05a5db3)">Diff</a>
> add section on RDF-star vocabulary

- cg-spec/2021-07-01-src.html
- cg-spec/2021-07-01.html
- cg-spec/index.html
waiting for all authors to join the CG
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/191.html" title="Last updated on Jul 1, 2021, 8:48 AM UTC (4db1ede)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/191/bd090df...4db1ede.html" title="Last updated on Jul 1, 2021, 8:48 AM UTC (4db1ede)">Diff</a>
> ready to publish new draft

- cg-spec/editors_draft.html
Some initial material taken from #169 from @pchampin.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/204.html" title="Last updated on Sep 8, 2021, 12:57 PM UTC (3dc0281)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/204/7dd0ab6...3dc0281.html" title="Last updated on Sep 8, 2021, 12:57 PM UTC (3dc0281)">Diff</a>
> Classes for RDF-star terminology

- cg-spec/editors_draft.html
the proposed text and figure address issue #203
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/206.html" title="Last updated on Sep 17, 2021, 11:55 AM UTC (f701c0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/206/1ccc91e...f701c0c.html" title="Last updated on Sep 17, 2021, 11:55 AM UTC (f701c0c)">Diff</a>
> paragraph and figure showing the interconnections between the sections

- cg-spec/editors_draft.html
Explanatory paragraph added to the end of Section 2.1.
***
<a href="https://pr-preview.s3.amazonaws.com/rdfguy/rdf-star/pull/210.html" title="Last updated on Oct 4, 2021, 3:25 PM UTC (1f3220b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/210/27e35a8...rdfguy:1f3220b.html" title="Last updated on Oct 4, 2021, 3:25 PM UTC (1f3220b)">Diff</a>
> Changes as per Issue #196

- ebnf/sparql.ebnf
- ebnf/sparql.html
... and referenced undefined UCHAR
> SPARQL IRIREF rule was from Turtle, and not the orignal spec

- cg-spec/editors_draft.html
This addresses issues #64 and #219.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/225.html" title="Last updated on Dec 6, 2021, 5:42 PM UTC (9640ada)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/225/44ba3f4...9640ada.html" title="Last updated on Dec 6, 2021, 5:42 PM UTC (9640ada)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/225.html" title="Last updated on Dec 15, 2021, 8:32 AM UTC (46f6a46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/225/a2d93d8...46f6a46.html" title="Last updated on Dec 15, 2021, 8:32 AM UTC (46f6a46)">Diff</a>
> Add a section in intro about "Common misconceptions"

- implementations.html
it was in the implementation report, but not on this page
@Tpt
> add Oxigraph in implementation page
